### ISSUE TITLE
Make system requirement

### ISSUE THREAD

**Issue by SeulGeek** [SeulGeek/FavRev#1]
- Make system requirement document

**Comment by SeulGeek** [comment]
Refer to the link below :

https://github.com/SeulGeek/FavRev/wiki

**Comment by SeulGeek** [comment]
@EldredRoer please review above link when you have time. thank you! :)

**Comment by EldredRoer** [comment]
This is great progress :)

I was wondering, for the map feature, whats the plan to show friend's reviews? Because I was thinking maybe on permission step, also request contact book access then on map launch check the contacts on device and compare with values in db and if exist, show on map. This was my thinking. Please share your idea for this flow :)

**Comment by SeulGeek** [comment]
Thank you! :)

yeah, that's good point! I thought the same at first. but I think we should consider the following cases.
There are two cases.
- User rejects to access their contacts. -> then there are no friends in the app. -> no display anything
- User doesn't want to add some friend from their contacts to the app. -> no display anything

In these case, I should display reviews on the map from users who have signed up to the app, not friends in the contact list.
So, I considered having access to contacts permission as a option.

Please tell me your opinion. :) @EldredRoer 

**Target scope**
1. user's contact list -> then it should request on the permission step.
2. all users of an app -> then it should request on "friends" tab

**Comment by EldredRoer** [comment]
Ahh ok I understand.  That way user can see other people's reviews besides friends :)

Doozo 👍

**Comment by EldredRoer** [comment]
I also just remembered something. in case user has bad network connection, they should still be able to add review. So in that case youre going to have to play with Room library so that you can save on device and once network is back up, sync with remote server and save there :)

**Comment by SeulGeek** [comment]
thanks! and is it better to use **service** to separate network function?

**Comment by EldredRoer** [comment]
hmm not unless youre planning on running app in background

**Comment by SeulGeek** [comment]
**SYSTEM REQUIREMENT**
DONE (V1) - EN, KO version
